export class SOLN {
    public ITM_CD: string;
    public QTY: string;
    public STORE_CD: string;
    public LOC_CD: string;
    public OUT_CD: string;
    public UNIT_PRC: string;
    public DEL_DOC_NUM: string;
    public DEL_DOC_LN_NUM: string;
    public COMM_CD: string;
    public REF_SER_NUM: string;
    public OUT_ID_CD: string;
    public SER_NUM: string;
    public SPIFF: string;
    public FILL_DT: string;
    public COD_AMT: string;
    public OOC_QTY: string;
    public PRC_CHG_APP_CD: string;
    public TAKEN_WITH: string;
    public WARRANTED_BY_LN_NUM: string;
    public TREATED_BY_LN_NUM: string;
    public DISC_AMT: string;
    public SET_UP: string;
    public LV_IN_CARTON: string;
    public SO_EMP_SLSP_CD1: string;
    public SO_EMP_SLSP_CD2: string;
    public PCT_OF_SALE1: string;
    public PCT_OF_SALE2: string;
    public COMM_ON_SETUP_CHG: string;
    public COMM_ON_DEL_CHG: string;
    public ACTIVATION_DT: string;
    public ACTIVATION_PHONE: string;
    public SHIP_GROUP: string;
    public TAX_CD: string;
    public TAX_BASIS: string;
    public CUST_TAX_CHG: string;
    public STORE_TAX_CHG: string;
    public TAX_RESP: string;
    public CO_CD: string;
    public FINAL_DT: string;
    public VOID_FLAG: string;
    public PURCHASE_ORDER_NUM: string;
    public CARRIER: string;
    public TRACKING_NUM: string;
    /**
     * Custom members
     */
    public NetLine: number;
    public Type: string;
    public Description: string;
    public Quantity_Ordered: number;
    public Quantity_Shipped: number;
    public Discount_Amount: number;
    public Calculated_NetLine_Amount: number;
    public SALE_Details_LINK: string;
}
